# FINANCIAL TECHNOLOGY & AUTOMATED INVESTING AUTOMATED INVESTING
## Overview and Origin
# Name of company
Betterment
Betterment is an online investment company based in New York City, registered with the Securities and Exchange Commission and a member of the Financial Industry Regulatory Authority (FINRA). It is also known as Betterment.com. Betterment is a registered investment advisor (RIA) and a broker-dealer.[2]
# When was the company incorporated?
Company founded 2008
Headquarters:	New York City, New York, United States
# Who are the founders of the company?
Jon Stein (Founder, CEO)
Eli Broverman (Co-Founder)
Key people: Dustin Lucien (Chief Operating Officer)
Products: Financial services, asset management, portfolio management, trust services. 
AUM: $22 billion (March 2020) [1] 
Parent:	Betterment Holdings, Inc.
Divisions:	Betterment for Business Betterment for Advisors
Website:	www.betterment.com
# How did the idea for the company (or project) come about?
Betterment was founded in 2008 in New York City by Jon Stein, a Columbia Business School MBA graduate, and Eli Broverman, a lawyer out of NYU School of Law. Stein and his roommate Sean Owen, a Google software engineer, started building the first online platform for Betterment in 2008 using a Java application and MySQL database on Apache Tomcat servers with an Adobe Flash- and Flex-based front-end design. Initial prototype designs were provided by Stein's then-girlfriend, Polina Khentov. Facing regulation associated with starting a financial company, Stein began negotiations to bring on Eli Broverman, then a securities lawyer he met over regular poker games, as a co-founder in 2008.[4]
# How is the company funded? How much funding have they received?
Betterment received Series A round funding from Bessemer Venture Partners in December 2010. By October 2012, Menlo Ventures provided Series B funding along with Bessemer Venture Partners and Anthemis Group. By 2012, the company established product offerings, such as IRAs, auto-deposit, auto-rebalancing, and goal-based investing advice.[9]
## Business Activities:
# What specific financial problem is the company or project trying to solve?
The company's personalized financial advice uses principles-based robo-advisor technologies such as computer algorithms. Licensed financial advisors provide over-the-phone consultations to customers who opt for additional support. Betterment’s primary retail platform offers individual retirement accounts, trusts, taxable investment accounts, and tax-coordinated asset location services.[10]
# Who is the company's intended customer?  Is there any information about the market size of this set of customers?
For younger investors who may not have a lot of money to put into the markets, the low-cost and technology advantages of robo-advisors can be attractive. As digital natives, perhaps the lack of human interaction is prized rather than admonished. For older, wealthier, or technology-averse investors, a financial advisor will provide more personalized service, a greater breadth of financial advice, and a real person-to-person relationship in many cases. Although financial advisors are more expensive and require larger starting amounts, and even though humans are prone to mistakes and implicit biases and errors, those costs and even those fallibilities can provide both value and solace. In the end, perhaps a hybrid approach is best—combining desirable aspects from each. [10]
# What solution does this company offer that their competitors do not or cannot offer? (What is the unfair advantage they utilize?)
Your Security and Trust Come First
We built systems around the principles of transparency, simplicity, and verification to ensure customer safety and security.
That’s why we designed our company—from the way we operate, to our people and our products—to improve upon traditional security, striving to provide as safe an investment environment as possible to consumers. We developed a vertically integrated structure as a way to deliver a premium customer experience through every step of the process. 
We are a custodial firm like Fidelity or Charles Schwab, which means we are responsible for handling your funds and keeping all the records of your assets. We handle your funds with maximum oversight from a number of overlapping regulators, and we also execute on a number of internal controls on a daily basis. 
We have two separate arms: the first, Betterment LLC, is an SEC-registered investment advisor, which operates the advice and investment platform you experience when you access your Betterment account. The  second arm, Betterment Securities, is a FINRA member broker-dealer, which executes trades on your behalf, and is the custodian of your assets. 
There are few institutions that are granted this privilege and with it comes duty. Betterment, Fidelity, Charles Schwab, and the few other qualified custodians are subject to the same set of strict capital requirements and regulatory oversight. These stringent requirements ensure your safety and help make us unique among other online investment managers, many of whom are introducing firms. Introducing firms have minimal capital requirements and in practice pass your funds through to another firm which custodies them. With Betterment, the only company you ever deal with is Betterment. 
Then, we go a step further with safety—employing principles of transparency, simplicity, and verification from the ground up to provide state-of-the-art security for every customer. 
You are protected in a crisis
First, it’s essential to know you are protected in the event of a worst-case scenario such as company insolvency. If our firm were to become insolvent in the future and funds were to go missing, your funds at Betterment Securities are protected by the Securities Investors Protection Corporation, or SIPC, up to $500,000 per account against those missing assets. 
To be sure, it’s extremely rare that a firm cannot return customer assets in a crisis, or that customers must rely on SIPC. To put things in perspective, over SIPC’s 42-year history, less than 1% of broker-dealers have been subject to SIPC proceedings. During those proceedings, 99% of assets distributed came from the insolvent broker-dealer’s estate (not from SIPC) and 99.94% of all claims were fully satisfied. 
Here is how the coverage works: if your account contained $1,500,000 and $1,000,000 was recovered, you would be made whole by SIPC. Each account at Betterment Securities that is a separate legal entity gets the full benefit of the $500,000 limit; if a Betterment customer has a  taxable account under his own name, a trust account, and an IRA account, each is eligible for up to $500,000 of SIPC protection. 
You can always verify your holdings
A key difference  between Betterment and many other portfolio managers is the level of transparency we provide our customers.  This is a function we created when we built the software behind Betterment—we wanted to make sure that our customers would be able to check their investments from any device and easily view what they were holding at all times. 
At Betterment you not only own independently verifiable securities from companies like Vanguard and iShares—your performance and precise positions are fully transparent at all times. You can follow your performance over any period of time, directly from your account. 
On any day, after any trade, we disclose the precise number of shares of every ETF in which you’re invested—that differentiates us from many portfolio and fund managers who do not openly share this information with clients. You can reproduce what we show on your own by plugging the results into any tracker. 
This also extends to the way we prepare our dividends reports and tax statements, where we don’t just show the transactions we have made on your behalf,  but we list each fractional share sold and the respective gross proceeds and cost basis for each. 
We check and double-check
Another way we improve security is embedded in the way we have built our systems to verify investments and transactions. Our investment platform has verification built in at every step—customers’ transaction amounts are reconciled with cash transfers and ACH transaction amounts, which are then reconciled with trade amounts, which are then reconciled with positions, and then with fills.
Key to achieving this efficiency and precision is more than a dozen daily reports which cross-check and reconcile every imaginable permutation of activity in our system to ensure that our records are always precise. 
For example, one report runs every night and adds up every single trade we’ve executed from the very inception of Betterment four years ago (over 13 million and counting), and makes sure the results add up the customer positions we have at the end of the day. These reports are designed to bring even the tiniest irregularity to our attention. Our operations team reviews every report daily. 
 When you deal with an introducing firm you are relying on the third party your funds have been passed on to — an organization you don’t really know — to perform these checks and have the precision you expect of Betterment. 
We undergo regular independent reviews
We  maintain our own books and records for all our customers’ assets—records that are routinely requested and reviewed by regulatory agencies. Our partner clearing firm also keeps its own records of all of the assets we manage for our clients, and we reconcile our records to our clearing firm’s reports on a daily basis, providing an additional independent source of verification. 
We also undergo regular, rigorous examination independently both by the SEC and by FINRA to ensure that we properly maintain our customer records and satisfy our capital requirements. Our regulators scrutinize our revenues, expenses and available capital on a monthly basis. Three separate annual audits by our independent public accountants verify the adequacy of our financial condition, the safety of our operational controls, and the safekeeping of customer assets we custody. Each examination ensures that our records match up with the independently available records from our clearing firm. 
This is yet another way we are more secure—the extent of our independent reviews is far beyond that of an introducing firm. 
We have expert management
Another piece of security is understanding who is accountable. Our management team includes financial and investment experts—with more than a century of combined investing experience. The investment advisor board includes esteemed professors and practitioners of finance at some of the most respected institutions in the world. 
That expertise and reputation extends to our funders, Bessemer Venture Partners and Menlo Ventures, two of the world’s premier venture capital funds with over $8 billion under management, and nearly 150 combined years of experience. Bessemer and Menlo share our vision that Betterment is the future of investing, and are closely involved in Betterment’s growth and operations. Our investors have deep expertise in the intersection between security, technology and financial services, which our management regularly benefits from.
We never commingle funds
Lastly, the way we handle our operations capital is yet another way we ensure the safety of your investments—and is a core part of our integrity as a company.  Our operational funds are always 100% segregated from any kind of customer investment activity, always in different accounts. All of our trading and money movement is fully automated, and our software is built from the ground up to make any sort of commingling impossible.
We do only one thing—manage your money—and we aim to do it perfectly. That means we don’t engage in any other financial operations that many other retail brokers do, such as proprietary trading with operating capital, or lending out customer assets.

As Betterment Securities is the custodian of your assets, we also maintain substantially higher levels of net capital than an introducing firm—another way we have a higher level of security than many other online investment managers.
We respect your trust
In an era where there is no greater commodity than trust, Betterment is an investment manager that adheres to the highest fiduciary and ethical standards, in line with our overall mission of transparency. Our customers have the best of both worlds in that we operate as a major financial institution, required to keep a large capital cushion, maintain our own records, and undergo extensive examination by regulators and public accountants, but we never put our financial cushion at risk and we never let customer assets out of our hands.
Not only does our structure provide maximum safety and transparency—serving as custodian also allows us to fix many “business as usual” inefficiencies endemic to the financial industry. We built a myriad of automated cost-saving efficiencies and delightful features into our platform, which a firm forced to rely on low-tech third parties can never replicate. Ultimately, we deliver a safer and more efficient investment service for you. [2]

#  Which technologies are they currently using, and how are they implementing them? 
This may take a little bit of sleuthing–– you may want to search the company’s engineering blog or use sites like Stackshare to find this information.)
## Landscape:
# What domain of the financial industry is the company in?
Robo-advising
# What have been the major trends and innovations of this domain over the last 5-10 years?
The flow of funds into robo-adviser accounts is expected to accelerate because of new federal regulations that require all financial professionals to put their customers’ interests first, at least when providing advice on their tax-advantaged retirement accounts. The rules, issued by the Labor Department, are expected to push more customers into lower-cost investments.
Aite predicts that robo-advisers will collect nearly $285 billion by 2017, still a small portion of the $20 trillion in retail investors’ assets held at brokerage firms and registered investment advisory firms.
Robo-advisers were already required to follow the highest standards of consumer protection — on every dollar they manage, not just retirement money — because most of them are registered investment advisers. That means they are required to act as fiduciaries, the legal term meaning they must put customers ahead of all else. And it’s a banner the robo-advisers wave proudly.
Given their status, the Labor Department, which oversees retirement accounts, has essentially given the robo-advisers its blessing, since many firms avoid the conflicts of interest embedded in the way the brokerage industry and its armies of representatives conduct their businesses.
But at the same time, other regulators have raised concerns about whether robo-advisers are thorough enough when gathering information about investors. A robo-adviser does not ask about money held outside of its service, for example, which can provide a distorted picture of a customer’s financial standing. Others argue the robo-advisers try to wiggle out of too much responsibility in their customer agreements.
The Massachusetts Securities Division recently put investors and the state-registered investment advisers it oversees — or those with less than $100 million in assets — on notice. In a paper issued this month, it bluntly stated that it did not believe an algorithm alone was capable of serving as a fiduciary, at least not the way robo-advisers are structured now. 
“I am not sure that many investors, in many cases, can be adequately taken care of by answering questions,” said William F. Galvin, Massachusetts secretary of the commonwealth, who likened the services to driverless cars. “You need a human that is responding to them.’’ 
Arthur Laby, a professor at Rutgers Law School, said investment advisers, as fiduciaries, can limit the breadth of their relationship with clients. Still, he does not view robo-advisers as fiduciaries in the traditional sense because of their inability to address subtleties that may arise in conversation. 
“They are not able to provide the kind of personalized advice that a customer can get from a human on the phone or sitting across the desk, where the customer can say: ‘Oh, I have a new wrinkle. I might be inheriting assets in the next 12 months,’” he said. “Or: ‘I may need to care for a sick parent. How will that impact the cash I need?’” 
Many robo-advisers say they make their limits clear, noting they are not in the business of providing full-scale financial planning. But often that kind of information is buried in the fine print. 
Being a “fiduciary is not about the types of service you offer, it’s about the quality of service,” said Adam Nash, chief executive of Wealthfront, a robo-adviser managing more than $3 billion. “There are financial planners helping you figure out what type of house you should buy. It’s not required that everyone do that.” 
The Massachusetts regulator and other industry critics argue that robo-advisers should go further, evaluating assets held elsewhere before investing customers’ money. (Wealthfront and Betterment already have technology in place that lets customers connect as many accounts to their services as they would like, giving the firms a bird’s-eye view of a client’s assets. But for now, they do not factor that into their investment analysis.) 
So exactly how deep are robo-advisers required to go? The law and legal precedents that govern investment advisers, and that shaped fiduciary duty, do not specifically spell that out. But several legal experts seem to agree that advising on a portion of an investor’s financial life is perfectly fine. 
“It is not unusual for clients to expressly or secretly withhold information from their advisers about other assets,” said Mercer E. Bullard, a professor at the University of Mississippi School of Law. “For example, if a 35-year-old says, ‘I’m not going to tell you what other assets I own and I want you to invest $100,000 for my retirement,’ you can do that with disclosure that the allocation might be different if you knew all of their assets.” 
Kara M. Stein, a commissioner at the Securities and Exchange Commission, recently said the idea of a robot that generates advice certainly bumps up against the traditional view of a fiduciary, which is based on a human relationship. 
“We should be asking whether these new robo-advisers can be neatly placed within our existing laws,” she said in a November speech. “Or, do we need certain tweaks and revisions?” 
Mary Jo White, chairwoman of the SEC, said in a March speech that as part of the commission’s effort to monitor emerging automated investment models, staff members from its exam program were looking into robo-advisers. “Through these inspections,” she said, “we deepen our knowledge of the range of services provided, as well as the challenges associated with different automated models.” 
And last May, the SEC and the Financial Industry Regulatory Authority, or FINRA, jointly issued an investor alert on automated investment services that highlighted their risks and limitations. For example, these services may suggest a certain mix of investments, the regulators said, but not realize that the investor needs some of the money in a few years to buy a new home. 
There is also a hybrid breed of robo-adviser, with human advisers who rely heavily on computer-driven portfolios. These include Personal Capital and Vanguard Personal Advisor Services. 
FINRA issued a report just last month, providing guidance for investors and advisers using such automated services. The report suggested that investors evaluate whether a firm is gathering enough information to understand their needs and stomach for risk. 
The report said Cerulli Associates, a research firm, had compared the stock-to-bond mix across seven digital advice providers, based on a 27-year-old investing for retirement. The suggested stock allocations ranged from as high as 90 percent to as low as 51 percent. 
Melanie L. Fein, a lawyer formerly with the Federal Reserve who now represents financial institutions, has written two papers critical of the robo-advisers. (The first was commissioned by Federated Investors, an investment management firm.) 
Her biggest concern echoes that of the Massachusetts regulator: Robo-advisers do not take a customer’s entire portfolio into account before making recommendations. She also argues that some providers are not free of conflicts and that their agreements put the onus on a customer to determine whether an investment strategy is right for that person. 
“The robo-advisers do seem to skirt the edges of fiduciary law,” she said. “It seemed they were putting a lot of responsibility on the investor, which is fine, but it is a question of how they present themselves.” 
For investors contemplating using robo-advisers, perhaps the most important point is to fully understand their limits. Consumers “have to be aware of what they do and what they don’t do,” Fein said, “and then make their decision.
# What are the other major companies in this domain?
•	Betterment
•	FutureAdvisor
•	Personal Capital
•	Vanguard Personal Advisor
•	Wealthfront
•	WiseBanyan
•	SigFig Wealth Management
•	Schwab Intelligent Portfolios
•	SoFi Wealth
•	Wealthsimple
•	Ellevest
Betterment is the largest independent robo advisor. Other big names are Schwab Intelligent Portfolios or Fidelity Go. 
Betterment doesn't own any of the funds it recommends. It's also a fiduciary, meaning it's legally bound to act in your best interest. So, you can have the peace of mind that the platform is working for you.

## Results
# What has been the business impact of this company so far?
With more than $250 billion currently under management in the U.S., various industry studies predict that the amount managed by robo-advisors will continue to grow at a torrid pace. At one point, many even predicted that robo services would drastically reduce or eliminate the need for traditional advisors. 
Clearly, the demise of the human financial advisor has been greatly overstated. While robo-advice has disrupted the advice industry, it has by no means replaced humans. In fact, the technology has generally served to enhance the delivery of advice. 
Take, for example, Vanguard’s offering, Vanguard Personal Advisor Services. Vanguard's platform is a combination of robo technology and human advice and has been widely successful in terms of drawing assets. And robo-investing pioneer Betterment now offers options where clients can interact with a human advisor as well as a platform that allows human advisors to use Betterment's platform for their own clients. 
Robo-advisors do not use a whole lot of AI in their implementation so far. In fact, the majority of them simply automate portfolio strategies that fit with some version of modern portfolio theory (MPT) and build optimized passive indexed portfolios. They then continuously scan and rebalance client portfolios but the investment strategy is not informed by any sort of machine learning. Still, these companies are looking for ways to use AI to enhance MPT through strategies like smart beta investing. 
Where AI is more prevalent is on Wall Street where professional trading desks have put it to use to model the economy and the market and to predict what will happen in the near-term. High-frequency trading (HFT) desks also use AI to come up with new and novel trading strategies that operate on the scale of milliseconds. When traders use AI in their HFT algorithms, the trading systems adapt on their own to changing market conditions that occur below the level of human perception, and often time neither the traders using them nor the software engineers that built these bots actually know what is going on under the hood or why the HFT algo does what it does! 
AI for Ordinary Investors
If you aren't a Wall Street trader, you can still find ways to take advantage of the purported benefits of artificial intelligence in picking stocks or timing the market - but it won't be found through most roboadvisors. Instead, several exchange traded funds (ETFs) have sprung up that use professional AI techniques and then allow ordinary investors to buy into that strategy through shares in its ETF. 
 Several ETFs invest in the AI sector (companies involved in developing or using AI) but do not use AI in their portfolio selection process. Be careful to note which strategy an ETF is using before buying.
"Artificial ETFs" are intelligent ETFs that are chosen and managed by computer programs that follow set rules and analyze funds to find the best performers within the constraints of the given rules. Since 2017 several different artificial intelligent ETFs have started and they are doing well against the rest of the funds market. The sheer number of stocks they are able to analyze gives them the advantage over traditionally-managed intelligent ETFs. 
One example is the "AI Powered ETF" (NASDAQ: AIEQ). From the fund's prospectus, it states: "AIEQ uses artificial intelligence to analyze and identify US stocks believed to have the highest probability of capital appreciation over the next 12 months, while exhibiting volatility similar to the overall US market. The model suggests weights based on capital appreciation potential and correlation to other included companies, subject to a 10% cap per holding. It is worth noting that while AIEQ relies heavily on its quantitative model, the fund is actively managed, and follows no index." 
It is too early to tell whether AI-powered funds like AIEQ will beat the broader market over the long-run.
Looking to the Future
There is much speculation about what the next frontier of AI will move out of Wall Street and into the financial advisory industry. Many believe that the next step is for AI to better facilitate advisors' relationship management as opposed to making purely trading decisions. As an example, an advisor could use AI during a client meeting to call up specific client information and model the performance of potential recommendations, a task that previously would have taken a team of analysts several hours or more. 
While many of today’s financial planning programs do offer these capabilities, AI's growth will only serve to expand software's analytical and predictive power. This is augmented by AI's deep learning capabilities, which will relieve advisors from having to perform much of the rote or mundane monitoring and administrative tasks that currently occupy a significant portion of their time. For example, an AI-based system could be set-up to monitor client portfolios and send a signal to the advisor when allocations fall outside of certain parameters. 
While AI could conceivably eliminate some roles for human advisors or support personnel, AI's analytical capabilities will likely result in the growth of more specialized, interpretive roles as well. The adoption of Artificial Intelligence will free up advisor time for increased client-facing activities: it's unlikely that advisors will ever want to just let their systems spit out data and analysis directly to a client without some review of this output.
Automating Client Service
It's likely that many of your clients' inquiries are questions that could be handled by an AI-driven assistant, guided by parameters that you set. This virtual assistant could perform an analysis of the client’s question and have some suggested alternatives ready for you to review and discuss. 
This system could be set so that there is continual analysis of your client’s financial picture, suggesting options as the client’s situation evolves. Perhaps they have a loan that could be refinanced or there has been a recent change in the tax law that would trigger the system to automatically review the impact on all of your clients. 
Similarly, if there were a significant change in the management of a mutual fund used in one or more client portfolios, your AI-based assistant could trigger an alert for the advisor to determine whether that fund should be retained or replaced. 
Costs of Falling Behind
While these scenarios may seem futuristic, many of them are already being implemented by industry giants. Lagging behind in technology can pose a huge risk to advisors, especially those that are working with the next generation of tech-savvy millennial and Generation X clients. These generations are on track to be the beneficiaries of the largest intergenerational transfer of wealth in history and expect their advisors to work with them on their terms. 
While AI and related technologies have not replaced human financial advisors and are unlikely to do so, AI will enhance advisor’s analytical capabilities and automate a number of mundane back-office tasks, reducing costs across the board. AI and other technologies are a tool and advisors who wish to continue to prosper will need to continuously stay on top of these technologies and strategically incorporate them into their practices. [11]

# What are some of the core metrics that companies in this domain use to measure success? How is your company performing, based on these metrics?
Normalized Benchmarking is a method to compare portfolios with differing equity and fixed income allocations. 
The percentage allocated to equities in a portfolio is one of the largest drivers of returns. Because of this, comparing two portfolios that have a different level of equity allocation is difficult and can be misleading. 
Normalized Benchmarking controls for differences in equity holdings by adjusting the benchmark to match the equity/fixed income ratio of the portfolio. 
When this is done across a group of portfolios, the portfolios can then be measured against each other by their return above or below the benchmark specific to the portfolio. Below is a more detailed explanation of how the benchmark is constructed and used.

To begin, one must define the universe of portfolios that will be analyzed. For our purposes, we analyzed taxable accounts at robo advisors as one universe, and retirement accounts at robo advisors as a separate universe. 
To construct the Normalized Benchmark, each portfolio within the investment universe must be separated into a portfolio of equity holdings and a portfolio of fixed income holdings (cash is included with the fixed income). This means that for each robo portfolio in a universe, we now have two portfolios, one made up of fixed income and one made up of equities. We then take all of the equity portfolios, equal weight them, and make them into one Equity Aggregate Portfolio. This portfolio contains a piece of every fund held in each equity portion of the portfolios. The same is done for fixed income. 
After this step is completed, each aggregate portfolio is analyzed to determine the type and weight of assets held in each. The Equity Aggregate Portfolio is analyzed to determine the allocation of the portfolio to domestic equities and the allocation to international equities. For the Fixed Income Aggregate Portfolio, allocations to the following categories are determined: municipal bonds, investment-grade corporate bonds, high-yield corporate bonds, foreign emerging markets debt, foreign developed markets debt, TIPS, short-term treasuries (0-3 year maturities), mid-term treasuries (3-10 year maturities), long-term treasuries (maturities of 10 years or greater), multi-sector bond funds, and cash. 
Next, we select a broad-based, passive, low-cost, commonly used ETF to represent each asset type. For example, the Vanguard Total Stock Market and Vanguard Total International Stock Market ETFs are used for the domestic and international positions in the equity benchmark portfolio, respectively. These are widely used, highly liquid, low-cost ETFs that are representative of the type of asset to which they are assigned. 
We then match the weight of the selected ETFs to the allocation of the corresponding asset types within its respective aggregate portfolio. For example, the amount of the Vanguard Total Stock Market ETF in the Equity Portfolio of the Normalized Benchmark matches the weight of domestic stocks in the Equity Aggregate Portfolio. This creates the Equity and Fixed Income Portfolios of the Normalized Benchmark that represent the robo portfolios’ equity and fixed income holdings, respectively. 
Now that we have constructed the Equity and Fixed Income Normalized Benchmark Portfolios, we can use it to compare performance across accounts within the previously determined investment universes. To compare an account, we first determine the initial target asset allocations to equity and fixed income, including cash. Next, we take note of significant shifts to these target allocations and when they occur. Then, we proportion the Equity and Fixed Income Portfolios of the Normalized Benchmark to match that of the portfolio being compared. For example, if we are measuring a portfolio with 60% equities and 40% bonds and cash, we create a benchmark that is made up of 60% of the equity benchmark and 40% of the fixed income benchmark. If we are measuring a portfolio with 65% equities and 35% fixed income, a benchmark is created, again using the Equity and Fixed Income Portfolios of the Normalized Benchmark, but in a 65% to 35% proportion. For portfolios that experienced significant shifts to their target allocations, their benchmark reflects these shifts. For example, if a portfolio experiences a shift from a 60% equity and 40% fixed income target allocation to a 55% equity and 45% fixed income target allocation on January 1, 2016, their Normalized Benchmark would reflect a 60% equity and 40% fixed income portfolio prior to January 1, 2016, and a 55% equity and 45% fixed income allocation thereafter. 
The Equity and Fixed Income Portfolios of the Normalized Benchmark are consistent, holding the same funds, in the same weights, regardless of the account you wish to compare, but the proportion of all of the equities and all of the fixed income changes to match the target allocation of the portfolio we are comparing. Therefore, a 65/35 portfolio is measured against a 65/35 benchmark, and a 70/30 portfolio is measured against a 70/30 benchmark. Each of the underlying equity and fixed income assets of the benchmark are consistent in each case, but the amount of the benchmark that is fixed income or equities changes to match the portfolio. 
After benchmarks are created, we introduce a 0.30% annual management fee to make the benchmark comparable to the fee charged by the most prominent robo advisors. 
Portfolios can then be measured based on their returns above or below the Normalized Benchmark. These returns for each portfolio above or below the Normalized Benchmark can then be compared to each other. This gives the investor a good idea of how the portfolios are performing, regardless of how much is in equities and how much is in fixed income.
Best Robo Advisors for 2020
Winner: SigFig
TD Ameritrade
Fidelity Go
TIAA
Vanguard
E*Trade Core
Betterment
The Robo Ranking has a new Best Overall Robo Advisor, as SigFig has taken the top spot from Fidelity Go. SigFig won because of its record of strong performance, low fees, and access to advisors at lower asset levels than many other providers. Over the 2.5-year analysis period used for this Ranking, SigFig had the best performance relative to its Normalized Benchmark and the best risk-adjusted performance measured by the Sharpe ratio. Its resulting performance score drove it to the top of the Ranking. However, SigFig has many attractive features beyond performance. [8]
# How is your company performing relative to competitors in the same domain?
Betterment would have outperformed the average investor with an investment advisor in 88% of all periods over the last decade.
When it comes to paying your investment fees, it’s a good idea to know exactly what you are buying. In the case of working with an investment advisor, you’re usually banking on getting some alpha, or returns that are above and beyond how the market is performing.

However, as a growing body of research shows, active portfolio management by an advisor doesn’t generally lead to better results for the individual investor. To be sure, the best advisors provide holistic planning value and the sort of smart, low-fee investing approach Betterment champions.
In a new analysis, we backtested the Betterment portfolio’s historical performance against the average returns earned by an investor using an advised portfolio with data assembled by Asset Risk Consultants, an independent investment consulting company. Over more than 30,500 periods, the Betterment portfolio outperformed those advisor-managed portfolios 88% of the time. The findings echo previous research that shows that an all index fund portfolio beats portfolios with active management in the vast majority of cases.
About the Data
The benchmark advised portfolio performance data comes from the ARC Private Client Indices which aggregates actual performance delivered to private clients by more than 60 major global investment managers.
The ARC data is broken up into four slices of equity risk, or Private Client Indices (PCIs.) It is available on a monthly basis, from January 2004 through the most recent completed quarter. This analysis focused on January 2004 through April 2014 (123 months) which offers 7626 possible periods (i.e. 123 possible one month periods, one possible 123 month period, and everything in between.) For each of those 7626 periods, we compared the closest equivalent Betterment portfolio with each of the four PCIs, resulting in 30,504 comparisons. We ran 30%, 50%, 70% and 90% Betterment portfolios against the Cautious, Balanced, Steady Growth, and Equity Risk PCIs, respectively.
The Betterment portfolios won 88.66% of the comparisons. Historical performance of the Betterment portfolio is based on the underlying ETFs, always net of fees. To the extent that an ETF was not in existence over the relevant period, performance is based on the index or asset class that the ETFs tracks. See full disclosure on how we compute historical performance. [6]


## Recommendations

# If you were to advise the company, what products or services would you suggest they offer? (This could be something that a competitor offers, or use your imagination!)
Betterment is one of the pioneers in the robo-advisory industry and is one of the first to use technology to recommend a portfolio and automate the investment process. Over the years since its founding in 2008, the firm has added additional asset classes, launching a savings product in July 2019 and a checking account in April 2020.
Betterment won awards in the following categories in our 2019 Robo Advisor Awards:
Best Overall Robo-Advisor
Best For Goal Tracking
Best For Beginners
Betterment is very much a goal-based platform, and there are many planning tools available to users along with plenty of advice. Benefi
Simple Asset Allocation— Betterment teaches the ropes to invest and, more importantly, proper asset allocation.
Low Management Fees— A flat-rate 0.25% annual fee for Betterment's automated service. 0.40%/year for its advisor service.
Perfect for Young Investors— Betterment makes investing accessible to young investors by automating the investing process.
Tax-Coordinated Portfolio— With tax and tax-deferred accounts at Betterment, it's possible to minimize the taxes you pay while investing.
RetireGuide Calculator— An easy-to-use retirement planner tool, although not as comprehensive as Personal Capital's Retirement Planner.
Flexible Portfolios— If you have $100,000 or more to invest, you can use Betterment's Flexible Portfolios to customize your asset allocation.
Analyze Accounts Beyond Betterment— Betterment will now let you analyze the retirement savings accounts you have outside its platform. This aggregation can help you keep your portfolios straight and well maintained.
Personalized Advice Packages— Betterment now offers advice packages created to answer your pressing financial questions, from getting started to retirement planning.
Goal-Based Investing— Betterment lets you align your investments -- including those outside the platform -- to your specific financial goals. [3]

# Why do you think that offering this product or service would benefit the company?
# What technologies would this additional product or service utilize?
# Why are these technologies appropriate for your solution?
Impact Investing with Robo-Advisors
Robo-advisors are algorithmic investment platforms that automate and optimize portfolio choices for individual investors with low costs and minimal human involvement. Traditionally, robo-advisors follow the logic of modern portfolio theory (MPT) to optimize a diversified portfolio across several asset classes and a philosophy that indexing is the best strategy for most investors. Indexing, however, implies that every stock in an index be held at its given weight in that index. Therefore, index investors will undoubtedly end up holding shares in companies that are not SRI or ESG-friendly.
To solve this issue, many robo-advisors now seek out exchange-traded funds (ETFs) that specialize in SRI and ESG investments and optimize portfolios in such a way as to approximate what modern portfolio theory would otherwise dictate. A robo-advisor can improve SRI investing for many investors that are doing it themselves: Some investors buy SRI funds that carry high management fees or sales loads, while robo-advisors seek out low-cost ETFs. Others screen for SRI stocks in such a way that they forgo the benefits of proper diversification against risk. These investors pick their own basket of SRI stocks, which can be a challenging and time-intensive approach. Robo-advisors can also automate portfolio rebalancing and engage in tax-loss harvesting to minimize tax exposure for investors.
What SRI Approaches do Robo-Advisors Use?
Each robo-advisor approaches SRI and ESG portfolio construction a little bit differently. Some platforms, like Earthfolio, only have SRI investment options and nothing else. Here, we will briefly describe some of the strategies used by popular broad-based robo-advisors:
Betterment seeks out SRI funds for U.S. large-cap stocks and emerging markets stocks only. According to their website, "Other asset classes, such as value, small-cap, and international stocks and bonds, are not replaced with an SRI alternative in our portfolio either because an acceptable alternative doesn't yet exist or because the respective fund's fees or liquidity levels make for a prohibitively high cost to you, our customers."2 Therefore the stocks, but not bonds, of companies like Exxon Mobile, Chevron, and Philip Morris may be excluded. [6]
The ETFs that Betterment uses in their SRI portfolios are DSI, SUSA, and ESGE.3
The Bottom Line
Socially responsible and ESG investing are gaining traction, especially with younger investors who also may be attracted to the technologically-focused investment platforms that robo-advisors provide. Several robo-advisors now offer socially-responsible or impact investing portfolios alongside their more traditional diversified index portfolios. While we only profile a few here, many more robo-advisors are beginning to include ESG funds in order to meet the demands of their users.

## Resources
https://www.betterment.com/
1.  "Form ADV Part 1". https://adviserinfo.sec.gov/
2. "Investment Safety and Security at Betterment". Betterment.com Resource Center
3. https://investorjunkie.com//?s=betterment
4. "The History of Betterment: How We Started a Company That Changed an Industry - Betterment". Betterment.com
5. “The pros and cons of using a robot as an investment adviser” https://www.boston.com/news/business/2016/04/29/pros-cons-using-robot-investment-adviser
6. https://www.betterment.com/resources/library/
7. https://www.betterment.com/press/
8. https://www.backendbenchmarking.com/blog/2020/08/the-robo-ranking-best-overall-robo/
9."Betterment Raises $10 Million Series B Financing from Menlo Ventures, Bessemer Venture Partners, & Anthemis Group - Betterment". Betterment.com
10. https://www.investopedia.com/financial-advisor/how-ai-shaping-advisory-landscape/
11. "Robo-Advisor 'Betterment' Adds Human Advice". CNBC.

